### ISSUE TITLE
Support for a forward proxy

### ISSUE THREAD

**Issue by flaccid** [uzyexe/dockerfile-newrelic#16]
Some environments may not have access to the internet without proxy.
https://docs.newrelic.com/docs/servers/new-relic-servers-linux/installation-configuration/linux-configuration-new-relic-servers

**Comment by uzyexe** [comment]
@flaccid Merged. thank you.
`FORWARD_PROXY` environment variable has enabled with the latest or 2.3.0.132 image tag now.

**Comment by flaccid** [comment]
https://github.com/rancher/community-catalog/pull/602/files created. Might be a good idea to include a basic `docker-compose.yml` in this repo too.

**Comment by uzyexe** [comment]
@flaccid Oh, thank you. I added that.
https://github.com/uzyexe/dockerfile-newrelic/pull/19/files
